cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
]

cart/models.py
from django.db import models
from store.models import Product, Variation


class Cart(models.Model):
    cart_id = models.CharField(max_length=200, blank=True)
    date_added = models.DateField(auto_now_add=True)


    def __str__(self):
        return self.cart_id
    

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity
    
    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from django.urls import reverse
from category.models import Category


class Product(models.Model):
    product_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=200, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)


    def get_url(self):
        return reverse('product_details', args=[self.category.slug, self.slug])
    

    def __str__(self):
        return self.product_name


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)
    

variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variation(models.Model):
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    product_variation = []
    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST[key]

            try:
                variation = Variation.objects.get(products=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)
            except:
                pass
        
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
    cart.save()
    is_cart_item_exist = CartItem.objects.filter(product=product, cart=cart).exists()
    if is_cart_item_exist:
        cart_item = CartItem.objects.filter(product=product, cart=cart)

    ex_var_list = []
    id = []
    for item in cart_item:
       existing_variation =item.variations.all()
       ex_var_list.append(list(existing_variation))
       id.append(item.id)

    if product_variation in ex_var_list:
        #increase the cart item quantity
        index = ex_var_list.index(product_variation)
        item_id = id[index]
        item = CartItem.objects.get(product=product, id=item_id)
        item.quantity += 1
        item.save()
    else:
        item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        if len(product_variation) > 0:
            item.variations.clear()
            item.variations.add(*product_variation)
        cart_item.save()
    return redirect('cart')


def remove_cart(request, product_id, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0

        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)

store/views.py
from django.shortcuts import render, get_object_or_404
from cart.models import CartItem
from cart.views import _cart_id

from category.models import Category
from .models import Product
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 2)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

    context = {
        'products': paged_products,
        'product_count': product_count
    }
    return render(request, 'store/store.html', context)


def product_details(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category_slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exist()
    except Exception as e:
        raise e
    
    context = {
        'single_product': single_product,
        'in_cart': in_cart,
    }

    return render(request, 'store/product_details.html', context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()

    context = {
        'products': products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context)


templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->
        {% if not cart_items %}
        <h2 class="text-center">Your Shopping Cart Is Empty</h2>
        <br>
        <div class="text-center">
            <a href="{% url 'store' %}" class="btn btn-primary">Continue Shopping</a>
        </div>
        {% else %}
        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm">
                                        </div>
                                        <figcaption class="info">
                                            <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{
                                                cart_item.product.product_name }}</a>
                                            <p class="text-muted small">
                                                {% if cart_item.variations.all %}
                                                {% for item in cart_item.variations.all %}
                                                {{ item.variation_category | capfirst }} : {{ item.variation_value |
                                                capfirst }} <br>
                                                {% endfor %}
                                                {% endif %}
                                            </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <form action="{% url 'remove_cart' cart_item.product.id cart_item.id %}"
                                                    method="post">
                                                    {% csrf_token %}
                                                    {% for item in cart_item.variations.all %}
                                                    <input type="hidden" name="{{ item.variation_category | lower}}"
                                                        value="{{ item.variation_value | capfirst}}">
                                                    {% endfor %}
                                                    <button class="btn btn-light" type="submit" id="button-plus"><i
                                                            class="fa fa-minus"></i></button>
                                                </form>
                                            </div>
                                            <input type="text" class="form-control" value="{{ cart_item.quantity }}">
                                            <div class="input-group-append">
                                                <form action="{% url 'add_cart' cart_item.product.id %}" method="post">
                                                    {%csrf_token %}
                                                    {% for item in cart_item.variations.all %}
                                                    <input type="hidden" name="{{ item.variation_category | lower}}"
                                                        value="{{ item.variation_value | capfirst}}">
                                                    {% endfor %}
                                                    <button class="btn btn-light" type="submit" id="button-minus"><i
                                                            class="fa fa-plus"></i></button>
                                                </form>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">${{ cart_item.sub_total }}</var>
                                        <small class="text-muted"> ${{ cart_item.product.price }} </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}"
                                        class="btn btn-danger" onclick="return confirm('Are you sure?')"> Remove</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <aside class="col-lg-3">

                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">${{ total }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> ${{ tax }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Grand Total:</dt>
                            <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static './images/misc/payments.png' %}" height="26">
                        </p>
                        <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                        <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->

            </aside> <!-- col.// -->


        </div> <!-- row.// -->
        {% endif %}
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/product_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <a href="#"><img src="{{ single_product.images.url }}"></a>
                        </div> <!-- img-big-wrap.// -->

                    </article> <!-- gallery-wrap .end// -->
                </aside>
                <main class="col-md-6 border-left">
                    <form action="{% url 'add_cart' single_product.id %}" method="post">
                        {% csrf_token %}
                        <article class="content-body">

                            <h2 class="title">{{ single_product.product_name }}</h2>

                            <div class="mb-3">
                                <var class="price h4">${{ single_product.price }}</var>
                            </div>

                            <p>{{ single_product.description }}</p>


                            <hr>
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Choose Color</h6>
                                    <select name="color" class="form-control" required>
                                        <option value="" disabled selected>Select Color</option>
                                        {% for i in single_product.variation_set.colors %}
                                        <option value="{{ i.variation_value | lower}}">{{ i.variation_value | capfirst}}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div> <!-- row.// -->
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Select Size</h6>
                                    <select name="size" class="form-control" required>
                                        <option value="" disabled selected>Select Size</option>
                                        {% for i in single_product.variation_set.sizes %}
                                        <option value="{{ i.variation_value | lower}}">{{ i.variation_value | capfirst}}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div> <!-- row.// -->
                            <hr>
                            {% if single_product.stock <= 0 %} <h5 class='text-danger'>Out of stock</h5>
                                {% else %}
                                <button type="submit" class="btn  btn-primary"> <span class="text">Add to Cart</span>
                                    <i class="fas fa-shopping-cart"></i> </button>
                                {% endif %}
                        </article> <!-- product-info-aside .// -->
                    </form>
                </main> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

        <br>

        <div class="row">
            <div class="col-md-9">

                <header class="section-heading">
                    <h3>Customer Reviews </h3>

                </header>

                <article class="box mb-3">
                    <div class="icontext w-100">
                        <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
                        <div class="text">
                            <span class="date text-muted float-md-right">24.04.2020 </span>
                            <h6 class="mb-1">Mike John </h6>

                        </div>
                    </div> <!-- icontext.// -->
                    <div class="mt-3">
                        <p>
                            Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                            quis nostrud exercitation ullamco laboris nisi ut aliquip
                        </p>
                    </div>
                </article>



            </div> <!-- col.// -->
        </div> <!-- row.// -->


    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}